version: '3'
services:
  web:
    build: .
    command: uwsgi --http 0.0.0.0:8000 --module chasko_coffee_stop.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:PcC1zCfNUyznmaUn@db.pygaenyeyjuelcntrgkh.supabase.co:6543/postgres
      - DJANGO_SETTINGS_MODULE=chasko_coffee_stop.settings
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PcC1zCfNUyznmaUn
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"

volumes:
  postgres_data:
