version: '3'
services:
  web:
    build: .
    command: uwsgi --http 0.0.0.0:8000 --module chasko_coffee_stop.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/chasko_coffee_stop  # Use 'postgres' instead of the full container name
      - DJANGO_SETTINGS_MODULE=chasko_coffee_stop.settings
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: chasko_coffee_stop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
