[build]
  dockerfile = "Dockerfile"
  build_args = []

[services]
  [[services]]
  name = "web"
  docker = true
  dockerfile = "Dockerfile"

  [services.env]
  DATABASE_URL = "postgres://admin:admin@db:5432/chasko_coffee_stop"
  SECRET_KEY = "django-insecure-w!zzw2+j6i_le_e0^sb+=0+k1gkpq-@c=h0rij78b@udpq9%91"

# Optional: Define the PostgreSQL service if you're using it
[[services]]
name = "db"
image = "postgres:13"
env = { POSTGRES_DB = "chasko_coffee_stop", POSTGRES_USER = "admin", POSTGRES_PASSWORD = "admin" }

[volumes]
  postgres_data = {}
